// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestBookTest {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp(){
    System.setProperty("webdriver.chrome.driver", "/opt/Web-Driver/chromedriver");
    ChromeOptions chromeOptions = new ChromeOptions().setBinary("/usr/bin/brave-browser");
    driver = new ChromeDriver(chromeOptions);
    /*
      try {
      driver = new RemoteWebDriver(new URL("http://localhost:9515"), chromeOptions);
    } catch (MalformedURLException e) {
      throw new RuntimeException(e);
    }*/
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testBook() {
    driver.get("https://www.um.edu.ar/biblio/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.id("busqueda")).click();
    driver.findElement(By.id("busqueda")).sendKeys("Ingeniería de Software");
    driver.findElement(By.id("buscar")).click();
    assertThat(driver.findElement(By.linkText("INGENIERIA DEL SOFTWARE")).getText(), is("INGENIERIA DEL SOFTWARE"));
  }
}
